image: python:latest
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
cache:
  paths:
    - .cache/pip
    - venv/

before_script:
  - python -V  # Print out python version for debugging
  - pip install -U virtualenv
  - virtualenv venv
  - source venv/bin/activate
  - pip install -U twine
  - pip install -U pytest
  - pip install -U mypy

mypy:
  stage: test
  script:
    - mypy yaqd_control

pages:
  stage: deploy
  script:
    - echo "nothing to do"
  artifacts:
    paths:
    - docs
  only:
  - master
twine:
  stage: deploy
  script:
    - python setup.py bdist_wheel
    - python setup.py bdist_wheel --plat-name win32
    - python setup.py sdist
    - pip install -U dist/*any.whl
    - yaqd --version
    - twine upload dist/*
  artifacts:
    paths:
      - dist/*
  only:
    - tags
